version: "3.3"
services:
  discordmusicbot:
    build: ./
    restart: unless-stopped
    network_mode: host
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PREFIX=${PREFIX}
      - ADMINPREFIX=${ADMINPREFIX}
      - ADMINS=${ADMINS}
    volumes:
      - ./Music:/usr/src/app/Music